### ISSUE TITLE
Heterogeneous DataFrame

### ISSUE THREAD

**Issue by Kriyszig** [Kriyszig/magpie#2]
There has been a slight change in plans. There will be an attempt to check out heterogeneous DataFrames.

#### Changes
Usage:
```d
DataFrame!(double, 20) df;
```
This will initialling a DataFrame with 20 columns of type `double`. These columns will represent data and not indexes. Indexes will be string based (with an added optimisation for integers) .

Similarly
```d
DataFrame!(double, 5, int, 5) df;
```
Will initialise a DataFrame with 5 `double` columns and 5 `integer` columns in the same order 

This work will be happening on a separate `experimental` branch (coming soon).

All the existing methods will be rewritten or modified over the weekend to accommodate these changes:

- `display()`
- `to_csv()`
- `from_csv()`

**Comment by Kriyszig** [comment]
Experimental is now live. -> [Jump to experimental](https://github.com/Kriyszig/magpie/tree/experimental)
:warning: <b>Warning</b> Code needs to be cleaned up. will be done by end of Monday [June 3rd IST].

**Comment by ZombineDev** [comment]
I would suggest using static arrays to simplify the implementation and improve potential error messages in the user's code:
Before:
```D
DataFrame!(int, 1, long, 2, double, 1, int, 5, float, 4, short, 9)
```

After:
```D
DataFrame!(int, long[2], double[1], int[5], float[4], short[9])
```

(For a single column of type `T`, either `T` or `T[1]` could be used.)

**Comment by Kriyszig** [comment]
Interesting thought. I'll add it by the end of the week.
Thanks for suggesting the improvement @ZombineDev :+1:

**Comment by ZombineDev** [comment]
You're welcome :)

BTW, I have an optimized structure of arrays  implementation, which you can use if you find useful. Just ping me if I forget to dig it up.
