### ISSUE TITLE
Publish on Dub registry

### ISSUE THREAD

**Issue by wilzbach** [Kriyszig/magpie#7]
This would allow people to try it out in a convenient way, e.g.

```d
/+dub.sdl:
dependency "magpie" version="*"
+/
import magpie.dataframe: DataFrame;
...
```

The dub registry requires at least one valid tag for adding it to the registry. However, this tag can be removed afterwards (and then you always get `~master`).

**Comment by Kriyszig** [comment]
Soory @wilzbach, I completely forgot about this :sweat_smile: 
I made a pre-release on Github and registered the package on DUB [here](https://code.dlang.org/packages/magpie)
